### ISSUE TITLE
GT boxes seem to be misaligned after processing with gt_vis.py

### ISSUE THREAD

**Issue by GodOfSmallThings** [salmank255/ROAD_Waymo_Baseline#1]
Hello, @salmank255 
After processing gt_vis.py with ROAD dataset, GT boxes seemed to be incorrect (or correct in some cases).

I looked into the code, and there were some magic numbers regarding width and height. Does using 691 for width and and 461 for height right for our case?
```python
gt_box[0] = (gt_box[0]/691)*org_width # width x1
gt_box[2] = (gt_box[2]/691)*org_width # width x2
gt_box[1] = (gt_box[1]/461)*org_height # height y1
gt_box[3] = (gt_box[3]/461)*org_height # height y2
``` 

Results above seems to be quite different from demo video in [here](https://sites.google.com/view/road-plus-plus/dataset). I attach some of results here.
![image](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/20166060/8d836456-84a7-4961-bef1-ba7f449136cf)
![image](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/20166060/5212bc3e-d4bd-4c37-bb22-c517f2620191)

**Comment by salmank255** [comment]
Hi @GodOfSmallThings,


The gt_vis.py file is based on our previous static dimensions that's why you are getting these visualization. In our recent code, we have updated this for the data loading which is based on dynamic image size not static the one we provided in this. 

Note our evaluation is still on --MIN_SIZE==600 on the eval ai platform as we want to have a fair comparison.

Thanks for spotting this out for visualization, we will update the gt_vis.py soon to make align with our data loading.

**Comment by salmank255** [comment]
Hi @GodOfSmallThings,

The visualization has been fixed you can pull the recent changes. Now the visualization is adaptive to the min_size in the argument. However, it's important to note for evaluation we fix the min_size to 600.

Attached are the snaps of the up
![Screenshot 2023-07-05 at 18 10 59](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/32925691/ef9a40ce-b0ef-430b-ad9d-faab9a1aa25f)
dated visualization. 
![Screenshot 2023-07-05 at 18 12 16](https://github.com/salmank255/ROAD_Waymo_Baseline/assets/32925691/b50392dc-70b7-4c70-b6dc-4e810d3ab000)
